#!/bin/bash
/root/AQM/blue/queuedata/read.sh
cp queuedata_blue.txt /home/samba_shared_dir
/root/AQM/blue/iproute2-3.1.0/tc/tc qdisc del dev eth0 root
rmmod /root/AQM/blue/queuedata/seqfile_queuedata_blue.ko
rmmod /root/AQM/blue/modules/sch_blue.ko

